### ISSUE TITLE
Build error in EF Core - Microsoft.EntityFrameworkCore" Version="3.1.7"

### ISSUE THREAD

**Issue by TheDanishDynamo** [bricelam/EFCore.Pluralizer#16] opened 2020-09-01 16:13 UTC
added package

Ran 

`dotnet-ef dbcontext scaffold "Server=*****;Database=****;Trusted_Connection=True;" Microsoft.EntityFrameworkCore.SqlServer -o Models`

Build Error

Note: 

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.1.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="3.1.7">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="3.1.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.7" />
  </ItemGroup>

</Project>
```

**Comment by ErikEJ** [comment] 2020-09-01 16:27
Please reformat your issue

**Comment by bricelam** [comment] 2020-09-01 18:04
What errors do you see when you run `dotnet build`?

**Comment by TheDanishDynamo** [comment] 2020-09-01 20:09
> What errors do you see when you run `dotnet build`?

It just says "Build Error" in red

**Comment by bricelam** [comment] 2020-09-22 20:21
Duplicate of https://github.com/dotnet/efcore/issues/12654

**Closed by bricelam** 2020-09-22 20:21 UTC
