### ISSUE TITLE
Table name of CommunicationStatus singularized to CommunicationStatu

### ISSUE THREAD

**Issue by ProfSantosh** [bricelam/EFCore.Pluralizer#14] opened 2020-04-09 11:52 UTC
Hello, Brice!
I'm having trouble using pluralizer on NETCore 3.1 + EFCore.3.1.2.

I have a table called `CommunicationStatus` and on `Scaffold-DbContext` the model it creates is called `CommunicationStatu` this only happened after installing the `EFCore.Pluralizer`

The leading `s` in Status should not be stripped out.

Thanks

**Comment by ErikEJ** [comment] 2020-04-09 12:18
Duplicate of #11 ?

**Closed** 2020-04-09 13:31 UTC
