### ISSUE TITLE
Wrong pluralization on some words

### ISSUE THREAD

**Issue by khaninejad** [bricelam/EFCore.Pluralizer#15] opened 2020-04-28 04:35 UTC
Hi,

Thanks for your package but when I use it in some words it's not working properly like "Status" word.
It changes Status to Statu.

If possible please fix this issue

**Comment by ErikEJ** [comment] 2020-04-28 05:09
Duplicate of #11

**Comment by bricelam** [comment] 2020-06-16 22:14
The pluralizer in this repo is intended to be fully compatible with the EF6 pluralizer. Any bug fixes or improvements to pluralization will break that compatibility.

EF Core 5.0 has been updated to use [Humanizer](https://github.com/Humanizr/Humanizer) (a much better pluralizer) by default during `dotnet ef dbcontext scaffold`.

**Closed by bricelam** 2020-06-16 22:14 UTC
