### ISSUE TITLE
Scaffolding with EFCore 3 for custom field names and Plurals

### ISSUE THREAD

**Issue by paulovila** [bricelam/EFCore.Pluralizer#9] opened 2019-11-27 16:02 UTC
It would be good to have the IPluralizer for scaffolding in netcore 3, and also being able to intercept names of any field in the schema, for example , if I had a SQL column called FXRate, I'd like that the scaffolding to respect that name or else I could intercept it and say
 ``` -UseDatabaseNames```  in ```Scaffold-DbContext``` doesn't respect the pluralization.

**Comment by bricelam** [comment] 2019-12-02 20:47
Duplicate of https://github.com/aspnet/EntityFrameworkCore/issues/12102

**Closed by bricelam** 2019-12-02 20:47 UTC

**Comment by ErikEJ** [comment] 2019-12-03 18:25
Working on this in EF Core Power Tools: https://github.com/ErikEJ/EFCorePowerTools/pull/317
