### ISSUE TITLE
Naming problem

### ISSUE THREAD

**Issue by JANA-syazdian** [bricelam/EFCore.Pluralizer#22] opened 2022-03-10 22:31 UTC
First of all Thanks for your library. It has helped us allot. 
Each time we run scaffold using your library, we have to fix some names;

1. The word "Status" . We have to rename one by one like follow
AssessmentStatu --> AssessmentStatus
2. In our work we have 
What is Scenario, we call it WIS
so we have to rename wherever we have it as follow:
RiskTotalByImpactWi --> RiskTotalByImpactWis

**Comment by bricelam** [comment] 2022-04-12 21:44
Duplicate of #14

The pluralizer in this repo is intended to be fully compatible with the EF6 pluralizer. Any bug fixes or improvements to pluralization will break that compatibility.

Feel free to fork this repo and/or use a better pluralizer like [Humanizer](https://github.com/Humanizr/Humanizer).

**Closed as completed by bricelam** 2022-04-12 21:44 UTC
Labels: duplicate
