### ISSUE TITLE
Won't work if parameter '-UseDatabaseNames' is used

### ISSUE THREAD

**Issue by figofan** [bricelam/EFCore.Pluralizer#17] opened 2020-09-14 04:34 UTC
This package works perfectly without parameter '-UseDatabaseNames', is there a workaround if I must use this parameter?

**Comment by ErikEJ** [comment] 2020-09-14 05:08
This has been fixed in EF Core 5.

**Comment by figofan** [comment] 2020-09-14 05:58
> This has been fixed in EF Core 5.

EF Core 5 won't come out until Nov, I guess I'll just add the plural manually. Thank you anyway!

**Comment by bricelam** [comment] 2020-09-22 20:05
Duplicate of https://github.com/dotnet/efcore/issues/12102

**Closed by bricelam** 2020-09-22 20:05 UTC

**Comment by bricelam** [comment] 2020-09-22 20:13
P.S. EF Core 5.0 RC1 does have a go-live license. There will only be a handful of additional bugs fixed between now and November 10.

**Comment by bricelam** [comment] 2020-09-22 20:16
In other words, you can think of RC2 and GA as the usual monthly patch releases but for early adopters.
